services:
  vote:
    image: pangpangmarran/voting-app:latest
    depends_on:
      redis:
        condition: service_healthy 
    ports:
      - "8080:80"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: "6379"
    networks:
      - back-tier

  result:
    image: pangpangmarran/result-app:latest
    depends_on:
      db:
        condition: service_healthy 
    ports:
      - "8081:80"
    environment:
      PG_HOST: db
      PG_PORT: "5432"
      PG_USER: postgres
      PG_PASSWORD: postgres
      PG_DATABASE: votes
    networks:
      - back-tier

  worker:
    image: pangpangmarran/worker-app:latest
    depends_on:
      redis:
        condition: service_healthy 
      db:
        condition: service_healthy 
    environment:
      REDIS_HOST: redis
      REDIS_PORT: "6379"
      DB_HOST: db
      DB_PORT: "5432"
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: votes
    networks:
      - back-tier

  redis:
    image: redis:alpine
    volumes:
      - "./healthchecks:/healthchecks"
    healthcheck:
      test: /healthchecks/redis.sh
      interval: "5s"
    networks:
      - back-tier

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: votes
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - "db-data:/var/lib/postgresql/data"
      - "./healthchecks:/healthchecks"
    healthcheck:
      test: /healthchecks/postgres.sh
      interval: "5s"
    networks:
      - back-tier

volumes:
  db-data:

networks:
  back-tier:
