plugin: amazon.aws.aws_ec2
regions:
  - eu-central-1
filters:
  instance-state-name: running
  tag:Name: "*annaa*"
keyed_groups:
  - prefix: frontend
  - prefix: backend
  - prefix: db
  - key: ec2_tags.Name
hostname_variable: tag:Name