[frontend]
annaas-instance-frontend ansible_host=ec2-18-198-209-90.eu-central-1.compute.amazonaws.com ansible_ssh_user=ubuntu ansible_ssh_private_key_file=~/.ssh/annaas-key
[backend]
annaas-instance-backend ansible_host=ec2-63-178-165-194.eu-central-1.compute.amazonaws.com ansible_ssh_user=ubuntu ansible_ssh_private_key_file=/.ssh/annaas-key
[database]
annaas-instance-db ansible_host=ec2-35-156-5-68.eu-central-1.compute.amazonaws.com ansible_ssh_user=ubuntu ansible_ssh_private_key_file=~/.ssh/annaas-key
