[frontend]
annaas-instance-frontend ansible_host=ec2-3-75-207-217.eu-central-1.compute.amazonaws.com ansible_ssh_user=ubuntu ansible_ssh_private_key_file=~/.ssh/annaas-key
[backend]
annaas-instance-backend ansible_host=ec2-3-78-227-224.eu-central-1.compute.amazonaws.com ansible_ssh_user=ubuntu ansible_ssh_private_key_file=/.ssh/annaas-key
[database]
annaas-instance-db ansible_host=ec2-35-158-234-167.eu-central-1.compute.amazonaws.com ansible_ssh_user=ubuntu ansible_ssh_private_key_file=~/.ssh/annaas-key
