[frontend]
annaas-instance-frontend ansible_host=63.176.97.110 ansible_ssh_user=ubuntu ansible_ssh_private_key_file=~/.ssh/annaas-key
[backend]
annaas-instance-backend ansible_host=10.0.2.100 ansible_ssh_user=ubuntu ansible_ssh_private_key_file=/.ssh/annaas-key
[database]
annaas-instance-db ansible_host=10.0.4.95 ansible_ssh_user=ubuntu ansible_ssh_private_key_file=~/.ssh/annaas-key
